import { type ParsedCliArgs } from "../parse.js";
export declare function runXmtpInit(args: ParsedCliArgs, configPath?: string): Promise<number>;
export declare function runXmtpInfo(configPath?: string): Promise<void>;
export declare function runXmtpStatus(configPath?: string): Promise<void>;
export declare function runXmtpResolve(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpOwnerAdd(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpOwnerList(configPath?: string): Promise<void>;
export declare function runXmtpOwnerRemove(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpTrustedAdd(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpTrustedList(configPath?: string): Promise<void>;
export declare function runXmtpTrustedRemove(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpPolicyInit(configPath?: string): Promise<void>;
export declare function runXmtpPolicyShow(configPath?: string): Promise<void>;
export declare function runXmtpPolicyValidate(configPath?: string): Promise<number>;
export declare function runXmtpPolicyEdit(configPath?: string): Promise<void>;
export declare function runXmtpDoctor(args: ParsedCliArgs, configPath?: string): Promise<number>;
export declare function runXmtpTestDm(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpGroupCreate(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpGroupAddMember(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpGroupList(args: ParsedCliArgs, configPath?: string): Promise<void>;
export declare function runXmtpRevokeOtherInstallations(configPath?: string): Promise<void>;
export declare function runXmtpRotateDbKey(configPath?: string): Promise<void>;
export declare function runXmtpRotateWallet(configPath?: string): Promise<void>;
