import Config

dotenv_values =
  Path.expand("../.env", __DIR__)
  |> File.read()
  |> case do
    {:ok, contents} ->
      contents
      |> String.split("\n")
      |> Enum.reduce(%{}, fn line, acc ->
        trimmed = String.trim(line)

        cond do
          trimmed == "" or String.starts_with?(trimmed, "#") ->
            acc

          true ->
            case String.split(trimmed, "=", parts: 2) do
              [key, value] ->
                normalized =
                  value
                  |> String.trim()
                  |> String.trim_leading("\"")
                  |> String.trim_trailing("\"")
                  |> String.trim_leading("'")
                  |> String.trim_trailing("'")

                Map.put(acc, String.trim(key), normalized)

              _ ->
                acc
            end
        end
      end)

    _ ->
      %{}
  end

env_or_dotenv = fn key, default ->
  System.get_env(key) || Map.get(dotenv_values, key, default)
end

# Configure your database
database_url = env_or_dotenv.("LOCAL_DATABASE_URL", env_or_dotenv.("DATABASE_URL", ""))

if is_binary(database_url) and String.trim(database_url) != "" do
  neon_ssl_required =
    String.contains?(database_url, "sslmode=require") or
      System.get_env("DB_SSL") in ["1", "true", "TRUE", "yes", "YES"]

  config :tech_tree, TechTree.Repo,
    url: database_url,
    ssl: neon_ssl_required,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
else
  db_user =
    env_or_dotenv.("DB_USER", env_or_dotenv.("PGUSER", System.get_env("USER") || "postgres"))

  db_pass = env_or_dotenv.("DB_PASS", env_or_dotenv.("PGPASSWORD", ""))
  db_host = env_or_dotenv.("DB_HOST", env_or_dotenv.("PGHOST", "localhost"))
  db_port = env_or_dotenv.("DB_PORT", env_or_dotenv.("PGPORT", "5432"))
  db_name = env_or_dotenv.("DB_NAME", "tech_tree_dev")

  config :tech_tree, TechTree.Repo,
    username: db_user,
    password: db_pass,
    hostname: db_host,
    port: String.to_integer(db_port),
    database: db_name,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tech_tree, TechTreeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "oBOiW0a4jPy8/G9Xq/7XAu9PcezPgEtbvDVtZyDtdbsFSYB3W+ba/a4tQ5ZmrkIm",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tech_tree, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tech_tree, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :tech_tree, TechTreeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/tech_tree_web/router\.ex$"E,
      ~r"lib/tech_tree_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tech_tree, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
