from __future__ import annotations

import json
import shutil
from dataclasses import asdict
from pathlib import Path

from .models import Capsule, MaterializedWorkspace


NOTEBOOK_TEMPLATE = """# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "marimo>=0.13.0",
# ]
# ///
import marimo

__generated_with = "0.13.0"

app = marimo.App()


@app.cell
def _():
    import json
    from pathlib import Path

    workspace = Path(__file__).resolve().parent
    task = json.loads((workspace / "task.json").read_text(encoding="utf-8"))
    protocol = (workspace / "protocol.md").read_text(encoding="utf-8")
    rubric = json.loads((workspace / "rubric.json").read_text(encoding="utf-8"))
    data_dir = workspace / "data"
    data_files = sorted(
        (
            {
                "name": path.name,
                "content": path.read_text(encoding="utf-8"),
            }
            for path in data_dir.iterdir()
            if path.is_file()
        ),
        key=lambda entry: entry["name"],
    )
    return workspace, task, protocol, rubric, data_files, json


@app.cell
def _(mo, task, protocol, data_files):
    steps = "\\n".join(f"{index}. {step}" for index, step in enumerate(task["protocol"], start=1))
    data_file_lines = "\\n".join(f"- `{entry['name']}`" for entry in data_files) or "- None"
    summary = mo.md(
        f'''
        # {task["title"]}

        **Capsule:** `{task["capsule_id"]}`  
        **Split:** `{task["split"]}`  
        **Source:** `{task["source_dataset"]}`

        ## Hypothesis
        {task["hypothesis"]}

        ## Protocol
        {steps}

        ## Data files
        {data_file_lines}
        '''
    )
    summary
    return


@app.cell
def _(workspace, task, rubric, data_files):
    verdict = {
        "status": "incomplete",
        "final_decision": "support",
        "summary": "Starter notebook generated by techtree-bbh-py.",
        "key_evidence": [
            f"Loaded {len(data_files)} data file(s).",
            f"Rubric contains {len(rubric.get('items', []))} item(s).",
        ],
        "rubric_claims": [
            {
                "rubric_item_id": item["rubric_item_id"],
                "satisfied": False,
                "evidence": "Starter notebook placeholder.",
            }
            for item in rubric.get("items", [])
        ],
        "notes": ["Replace this placeholder verdict before final validation."],
    }
    (workspace / "verdict.json").write_text(json.dumps(verdict, indent=2) + "\\n", encoding="utf-8")
    mo.md("Starter verdict written to `verdict.json`.")
    return


if __name__ == "__main__":
    app.run()
"""


def _prepare_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def materialize_workspace(
    capsule: Capsule,
    workspace_dir: Path,
    *,
    official_mode: bool = False,
    notebook_backend: str = "marimo-local",
    max_turns: int = 20,
) -> MaterializedWorkspace:
    _prepare_dir(workspace_dir)
    data_dir = workspace_dir / "data"
    artifacts_dir = workspace_dir / "artifacts"
    data_dir.mkdir(parents=True, exist_ok=True)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    task_json_path = workspace_dir / "task.json"
    protocol_md_path = workspace_dir / "protocol.md"
    rubric_json_path = workspace_dir / "rubric.json"
    analysis_py_path = workspace_dir / "analysis.py"
    verdict_json_path = workspace_dir / "verdict.json"

    _write_json(
        task_json_path,
        capsule.task_json(
            official_mode=official_mode,
            notebook_backend=notebook_backend,
            max_turns=max_turns,
        ),
    )
    _write_text(protocol_md_path, capsule.protocol_markdown())
    _write_json(rubric_json_path, capsule.rubric_json())
    _write_text(analysis_py_path, NOTEBOOK_TEMPLATE)
    _write_json(verdict_json_path, capsule.verdict_template())

    for data_file in capsule.data_files:
        _write_text(data_dir / data_file.name, data_file.content)

    _write_json(
        artifacts_dir / "workspace-manifest.json",
        {
            "capsule_id": capsule.capsule_id,
            "task_id": capsule.task_id,
            "split": capsule.split,
            "source_dataset": capsule.source_dataset,
            "analysis_py": analysis_py_path.name,
            "verdict_json": verdict_json_path.name,
            "data_files": [asdict(data_file) for data_file in capsule.data_files],
        },
    )

    return MaterializedWorkspace(
        capsule=capsule,
        workspace_dir=workspace_dir,
        task_json_path=task_json_path,
        protocol_md_path=protocol_md_path,
        rubric_json_path=rubric_json_path,
        analysis_py_path=analysis_py_path,
        verdict_json_path=verdict_json_path,
        data_dir=data_dir,
        artifacts_dir=artifacts_dir,
    )
